<?php
return [
    'ru' => [
        'home' => 'Главная',
        'search_users' => 'Поиск пользователей',
        'send_message' => 'Отправить сообщение',
        'chats' => 'Чаты',
        'write_blog' => 'Написать блог',
        'view_blogs' => 'Просмотр блогов',
        'logged_in_as' => 'Вы вошли как #',
        'register' => 'Регистрация',
        'login' => 'Вход',
        'username' => 'Имя пользователя',
        'password' => 'Пароль',
        'undo' => 'Отменить',
        'captcha_failed' => 'Капча не пройдена!',
        'captcha_choose' => 'Выбери картинку с',
        'message_limit' => 'Достигнут лимит сообщений!',
        'message_sent' => 'Сообщение отправлено!',
        'blog_posted' => 'Блог опубликован!',
        'search' => 'Поиск',
        'change_lang' => 'Сменить язык',
        'loading' => 'Загрузка...',
        'register_success' => 'Зарегистрировано! <a href="login.php">Войти</a>',
        'login_failed' => 'Ошибка входа!',
        'not_logged_in' => 'Сначала войдите!',
        'logout_random' => 'Вы были случайно разлогинены!',
        'captcha' => 'Капча',
    ],
    'kk' => [
        'home' => 'Басты бет',
        'search_users' => 'Пайдаланушыларды іздеу',
        'send_message' => 'Хабар жіберу',
        'chats' => 'Чаттар',
        'write_blog' => 'Блог жазу',
        'view_blogs' => 'Блогтарды көру',
        'logged_in_as' => 'Сіз # ретінде кірдіңіз',
        'register' => 'Тіркелу',
        'login' => 'Кіру',
        'username' => 'Пайдаланушы аты',
        'password' => 'Құпия сөз',
        'undo' => 'Болдырмау',
        'captcha_failed' => 'Капча дұрыс емес!',
        'captcha_choose' => 'Суретті таңдаңыз',
        'message_limit' => 'Хабарлама шегі жетті!',
        'message_sent' => 'Хабар жіберілді!',
        'blog_posted' => 'Блог жарияланды!',
        'search' => 'Іздеу',
        'change_lang' => 'Тілді өзгерту',
        'loading' => 'Жүктелуде...',
        'register_success' => 'Тіркелді! <a href="login.php">Кіру</a>',
        'login_failed' => 'Кіру қатесі!',
        'not_logged_in' => 'Алдымен кіріңіз!',
        'logout_random' => 'Сіз кездейсоқ шығып кеттіңіз!',
        'captcha' => 'Капча',
    ],
    'en' => [
        'home' => 'Home',
        'search_users' => 'Search Users',
        'send_message' => 'Send Message',
        'chats' => 'Chats',
        'write_blog' => 'Write Blog',
        'view_blogs' => 'View Blogs',
        'logged_in_as' => 'Logged in as #',
        'register' => 'Register',
        'login' => 'Login',
        'username' => 'Username',
        'password' => 'Password',
        'undo' => 'Undo',
        'captcha_failed' => 'CAPTCHA failed!',
        'captcha_choose' => 'Choose the image with',
        'message_limit' => 'Message limit reached!',
        'message_sent' => 'Message sent!',
        'blog_posted' => 'Blog posted!',
        'search' => 'Search',
        'change_lang' => 'Change Language',
        'loading' => 'Loading...',
        'register_success' => 'Registered! <a href="login.php">Login</a>',
        'login_failed' => 'Login failed!',
        'not_logged_in' => 'Login first!',
        'logout_random' => 'You have been randomly logged out!',
        'captcha' => 'CAPTCHA',
    ],
];
